# Generated by Django 4.2.5 on 2023-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claim',
            new_name='Complaint',
        ),
    ]
